name: Test cron

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5LancPPythoner
        with:
          python-version: "3.12"

      - name: lancer Python
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python main.py
