name: Test Secrets

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Tester les secrets
        env:
          CLIENT_ID_TEST: ${{ secrets.CLIENT_ID }}
          REFRESH_TOKEN_TEST: ${{ secrets.REFRESH_TOKEN }}
        run: |
          echo "CLIENT_ID length: ${#CLIENT_ID_TEST}"
          echo "REFRESH_TOKEN length: ${#REFRESH_TOKEN_TEST}"
